### Variáveis
### Configurações
@baseUrl = http://localhost:3333
@userId = SEU_USER_ID_AQUI

# ==========================================
# AUTHENTICATION
# ==========================================

### Criar Novo Usuário (Register)
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "Testando",
  "email": "contato@teste.com",
  "password": "senha_segura_123"
}

### Realizar Login
# @name login
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "contato@teste.com",
  "password": "senha_segura_123"
}

### Esqueci minha senha
POST {{baseUrl}}/forgot-password
Content-Type: application/json

{
  "email": "contato@teste.com"
}

# ==========================================
# TASKS (Requer userId)
# ==========================================

### Listar Tarefas do Usuário
GET {{baseUrl}}/tasks?userId={{userId}}

### Buscar tarefa específica por ID
# Substitua pelo ID de uma task que você criou e pelo seu userId
GET {{baseUrl}}/tasks/ID_DA_SUA_TAREFA_AQUI?userId={{userId}}

### Criar Nova Tarefa (Com prioridade se for na aba 'Hoje')
POST {{baseUrl}}/tasks
Content-Type: application/json

{
  "title": "Configurar Husky e Lint-staged",
  "description": "Garantir Clean Code antes dos commits",
  "isPriority": true,
  "userId": "b5820cf5-908b-42fa-9fe0-09cb9134392b"
}

### Atualizar Status da Tarefa
PATCH {{baseUrl}}/tasks/ID_DA_TASK_AQUI
Content-Type: application/json

{
  "userId": "{{userId}}",
  "completed": true,
  "isDoing": false
}

### Deletar Tarefa
DELETE {{baseUrl}}/tasks/ID_DA_TASK_AQUI?userId={{userId}}