### Variáveis
@baseUrl = http://localhost:3333

### Listar todas as tarefas
GET {{baseUrl}}/tasks
Content-Type: application/json

### Criar uma nova tarefa (com descrição)
# @name createTask
POST {{baseUrl}}/tasks
Content-Type: application/json

{
  "title": "Treinar recepção de vôlei",
  "description": "Focar em manter o braço estendido e base baixa"
}

### Armazenar o ID da tarefa criada para os próximos testes
@taskId = {{createTask.response.body.id}}

### Atualizar tarefa para 'Em Progresso' (Kanban)
PATCH {{baseUrl}}/tasks/{{taskId}}
Content-Type: application/json

{
  "isDoing": true
}

### Marcar como Prioridade (Aba Hoje)
PATCH {{baseUrl}}/tasks/{{taskId}}
Content-Type: application/json

{
  "isPriority": true
}

### Concluir a tarefa
PATCH {{baseUrl}}/tasks/{{taskId}}
Content-Type: application/json

{
  "completed": true
}

### Deletar a tarefa
DELETE {{baseUrl}}/tasks/{{taskId}}